name: Deploy to Cloudflare Pages
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # For this static site there is no build step required
      # - name: Build
      #   run: echo "No build needed"

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=${{ secrets.CLOUDFLARE_PAGES_PROJECT }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}